/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    ConfirmDialog: typeof import('./src/components/confirmDialog.vue')['default']
    CreatePoliceOfficer: typeof import('./src/components/CreatePoliceOfficer.vue')['default']
    CreatePoliceOfficerForm: typeof import('./src/components/CreatePoliceOfficerForm.vue')['default']
    CreateUser: typeof import('./src/components/CreateUser.vue')['default']
    CreateUserForm: typeof import('./src/components/CreateUserForm.vue')['default']
    DriverLicence: typeof import('./src/components/DriverLicence.vue')['default']
    FilterDeregistration: typeof import('./src/components/vehicleData/FilterDeregistration.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LoginView: typeof import('./src/components/LoginView.vue')['default']
    Navigation: typeof import('./src/components/Navigation.vue')['default']
    NewOwnerSide: typeof import('./src/components/NewOwnerSide.vue')['default']
    OfficersTable: typeof import('./src/components/OfficersTable.vue')['default']
    OwnerSide: typeof import('./src/components/OwnerSide.vue')['default']
    RegistrationLogs: typeof import('./src/components/vehicleData/RegistrationLogs.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/Search.vue')['default']
    SnackbarProvider: typeof import('./src/components/SnackbarProvider.vue')['default']
    UserDetails: typeof import('./src/components/UserDetails.vue')['default']
    VehicleOwnerSummary: typeof import('./src/components/vehicleData/VehicleOwnerSummary.vue')['default']
    VehiclesTable: typeof import('./src/components/vehicleData/VehiclesTable.vue')['default']
    VehicleSummary: typeof import('./src/components/vehicleData/VehicleSummary.vue')['default']
  }
}
